version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - pip install poetry
      - export PATH=$PATH:$HOME/.local/bin
      - poetry build
      - poetry install --with test

  build:
    commands:
      - poetry run pytest
      - poetry run python package
      - docker build -t $REPOSITORY_URI:$IMAGE_VERSION .

  post_build:
    commands:
      - docker tag $REPOSITORY_URI:$IMAGE_VERSION $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_VERSION
      - echo "Build completed on `date`" > build.log
      - echo "$IMAGE_VERSION" >> build.log

env:
  variables:
    AWS_DEFAULT_REGION: "eu-west-2"
    AWS_ACCOUNT_ID: "093380438279"
    REPOSITORY_URI: "093380438279.dkr.ecr.eu-west-2.amazonaws.com/dummy-codebuild-project"
    IMAGE_VERSION: "0.0.1"

artifacts:
  files:
    - build.log
