version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - export PATH=$PATH:$HOME/.local/bin
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - make codebuild

  post_build:
    commands:
      - docker tag $NAME $ECR_REPOSITORY_URI:$VERSION
      - docker push $ECR_REPOSITORY_URI:$VERSION

env:
  variables:
    NAME: "dummy-codebuild-project"
    AWS_DEFAULT_REGION: "eu-west-2"
    AWS_ACCOUNT_ID: "093380438279"
    ECR_REPOSITORY_URI: "093380438279.dkr.ecr.eu-west-2.amazonaws.com/dummy-codebuild-project"
    VERSION: "0.0.1"
