version: 0.2

phases:
  pre_build:
    commands:
      - make codebuild-setup

  build:
    on-failure: ABORT
    commands:
      - make codebuild-run

  post_build:
    commands:
      - make codebuild-push

cache:
  paths:
    - '/usr/share/doc/**/*'
    - '/usr/local/libexec/poetry-cache/**/*'
    - '/home/automation/.local/share/pypoetry/**/*'
