version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10

  build:
    commands:
      - make codebuild

# post_build:
#   commands:
#     - docker tag $(NAME):$(VERSION) "$(ECR_REPOSITORY_URI):$(VERSION)"
#     - docker push "$(ECR_REPOSITORY_URI):$(VERSION)"
#     - docker image rm "$(NAME):$(VERSION)"
